- name: This playbook installs nginx, configures nginx to use custom folder, deploys custom web page
  hosts: all
  roles:
  - nginx

- name: Verify if nginx web pages are accessible
  hosts: localhost
  tasks:
  - name: Access the web page hosted by nginx web server
    shell: "curl http://192.168.1.80:8{{item}}"
    with_sequence: start=1 end=4 format="%03d"
    register: output

  - debug: var=output

