- name: This playbook demonstrates invoking our custom ansible module
  hosts: localhost
  tasks:
  - name: Invoke custom hello module
    hello: message="Hello Module !"
    register: output

  - debug: var=output
