- name: Create custom web root folder
  file: path=/var/html mode=0755 state=directory 

- name: Retrieve IP address
  shell: hostname -i
  register: ipaddress

- name: Deploy custom web page
  template: src=index.html.j2 dest=/var/html/index.html 
