- name: Check if nginx web server is already running
  shell: curl localhost
  register: output
  ignore_errors: yes

- debug: var=output

- name: Start nginx web server in ansible Rocky nodes 
  when: output.rc != 0
  shell: nginx
